### ISSUE TITLE
Request for Dataset Availability

### ISSUE THREAD

**Issue by Gao-zy26** [RedAIGC/StoryMaker#1]
Thank you for sharing your excellent work and making the code available. I noticed that the dataset used in the paper isn't included in the repository. I was wondering if you have any plans to release the dataset? Access to the dataset would be very helpful for replicating your results. If sharing isn't possible, any guidance on obtaining similar data would be appreciated.

**Comment by RedAIGC** [comment]
Thanks for your attention. Due to company reasons, it is not convenient to make the dataset public. However, you can collect datasets from the Internet, such as laion-face/pexels/zcool,etc
