### ISSUE TITLE
About Comfyui

### ISSUE THREAD

**Issue by jasonlbx13** [RedAIGC/StoryMaker#10]
Amazing job！Do you interested in migrating it to the Comfyui？

**Comment by RedAIGC** [comment]
> Amazing job！Do you interested in migrating it to the Comfyui？

Thank you for your attention. We don’t have time to do it at this moment. If you are interested, you can help us, many thanks.

**Comment by tanglaoya321** [comment]
https://github.com/tanglaoya321/ComfyUI-StoryMaker
I've implemented it simply，give it a try

**Comment by jasonlbx13** [comment]
> https://github.com/tanglaoya321/ComfyUI-StoryMaker I've implemented it simply，give it a try我已经简单地实现了它，给它一个尝试

Thanks a lot!
