### ISSUE TITLE
about position embedding

### ISSUE THREAD

**Issue by ChdDongyang** [RedAIGC/StoryMaker#13]
Hi, thanks for your excellent work! Your paper mentioned “These embeddings are concatenated and augmented with positional embeddings ,i.e., Epos, which serve to distinguish different characters. ”，I want to know how the positional embeddings are designed here and how I can get it. Thanks very much!

**Comment by RedAIGC** [comment]
Thanks for  your attention, we just utilize a learnable parameter to represent the positional embeddings to distinguish different characters, please ref the code at https://github.com/RedAIGC/StoryMaker/blob/main/ip_adapter/ip_adapter_faceid.py#L73

**Comment by ChdDongyang** [comment]
> Thanks for your attention, we just utilize a learnable parameter to represent the positional embeddings to distinguish different characters, please ref the code at https://github.com/RedAIGC/StoryMaker/blob/main/ip_adapter/ip_adapter_faceid.py#L73

Thank you very much!
