### ISSUE TITLE
目前开放的权重，基模只支持sdxl吗？

### ISSUE THREAD

**Issue by CanvaChen** [RedAIGC/StoryMaker#17]

**Comment by JoshonSmith** [comment]
@RedAIGC 期待在更先进更强大的文生图基础模型上的 storymaker

**Comment by RedAIGC** [comment]
谢谢关注，我们正努力训练flux版本的模型，效果预期会更好的

**Comment by RedAIGC** [comment]
> @RedAIGC 目前base model只能使用YamerMIX_v11吗？还是任意基于sdxl微调的都可以呢？

可以适配任意sdxl模型，效果上可能会有所折损，可以试试看
