### ISSUE TITLE
how do apply openpose when do demo_swapcloth()

### ISSUE THREAD

**Issue by tianqyun111** [RedAIGC/StoryMaker#19]
i found controlnet_conditioning_scale in the pipeline_sdxl_storymaker.py is not for openpose_controlnet,how can i solve it ?

**Comment by RedAIGC** [comment]
> controlnet_conditioning_scale

Hi, we don't use controlnet during inference by default, you can ignore controlnet_conditioning_scale.

**Comment by tianqyun111** [comment]
> > controlnet_conditioning_scale
> 
> Hi, we don't use controlnet during inference by default, you can ignore controlnet_conditioning_scale.

Thank you for your reply. If I want to use ControlNet for the generation of clothswap, do I need to modify the pipeline myself? Can you give me some guidance

**Comment by RedAIGC** [comment]
> > > controlnet_conditioning_scale
> > 
> > 
> > Hi, we don't use controlnet during inference by default, you can ignore controlnet_conditioning_scale.
> 
> Thank you for your reply. If I want to use ControlNet for the generation of clothswap, do I need to modify the pipeline myself? Can you give me some guidance

That's simple, you can use the StableDiffusionXLControlNetPipeline and open-source pose controlnet model to generate your desired pose images.

**Comment by mf0212** [comment]
Can you tell me more details about how to generate images with pose control? Follow I see about combination SD Controlnet with openpose control ney don't allow to reference images. It generates images based on prompt and extracted pose. So can you give more detail about generating pose control from reference image and pose?  Can you upload your code for this, this will be my honor?
