### ISSUE TITLE
How to Perform Pose Control as Demonstrated in Example (E) of Diverse Applications

### ISSUE THREAD

**Issue by endman100** [RedAIGC/StoryMaker#2]
Hello, thank you for open-sourcing and sharing this research.
I would like to ask how to execute pose control, just like the example shown in (E) of the Diverse Applications.

**Comment by RedAIGC** [comment]
Thanks for your attention,  pose control is simple, you can prepare one target pose extracted from another image, and use the StableDiffusionControlNetPipeline and an open-source pose-controlnet model to generate target image.

**Comment by haoyuying** [comment]
we need to rewrite StableDiffusionXLStoryMakerPipeline  that inherits from StableDiffusionXLControlNetPipeline, right? Do you have some advices? thx
