### ISSUE TITLE
How to adjust generate parameters

### ISSUE THREAD

**Issue by diggle001** [RedAIGC/StoryMaker#21]
你好，我使用默认的参数，生成效果很差，不真实，人体动作不协调，场景不符合。请问这些参数该怎么调整好，各自会影响什么效果。

**Comment by RedAIGC** [comment]
> 你好，我使用默认的参数，生成效果很差，不真实，人体动作不协调，场景不符合。请问这些参数该怎么调整好，各自会影响什么效果。

目前的模型确实会有一些局限性，比如参考图最好是人物正脸无遮挡的，如果人体动作不协调可以试着加一个pose-controlnet控制一下，场景不符合可能需要调整下prompt看看，降低ip_adapter_scale/lora_scale也可以减少人脸过丑的问题
