### ISSUE TITLE
双人图像生成问题

### ISSUE THREAD

**Issue by 258863** [RedAIGC/StoryMaker#22]
你好，

在您的示例中，我看到了使用两个人物生成场景图像的例子，但示例代码中没有具体展示如何实现这一操作。我想了解如何操作。您能否提供一些具体的操作步骤或代码示例，帮助我理解如何结合两个人物的图像和文本提示生成一张新图像？

谢谢！

**Comment by RedAIGC** [comment]
> 你好，
> 
> 在您的示例中，我看到了使用两个人物生成场景图像的例子，但示例代码中没有具体展示如何实现这一操作。我想了解如何操作。您能否提供一些具体的操作步骤或代码示例，帮助我理解如何结合两个人物的图像和文本提示生成一张新图像？
> 
> 谢谢！

我们在infer.py代码里有双人生成的示例，你可以试试看 https://github.com/RedAIGC/StoryMaker/blob/main/infer.py

**Comment by 258863** [comment]
> > 你好，
> > 在您的示例中，我看到了使用两个人物生成场景图像的例子，但示例代码中没有具体展示如何实现这一操作。我想了解如何操作。您能否提供一些具体的操作步骤或代码示例，帮助我理解如何结合两个人物的图像和文本提示生成一张新图像？
> > 谢谢！
> 
> 我们在infer.py代码里有双人生成的示例，你可以试试看 https://github.com/RedAIGC/StoryMaker/blob/main/infer.py

好的，非常感谢

**Comment by 258863** [comment]
请问风格话是如何实现的，因为图像对文本的表达能力可能不如flux, 我想先用flux生成图片，然后作为风格图片，增强其为本对图像的表达能力。

**Comment by RedAIGC** [comment]
> 请问风格话是如何实现的，因为图像对文本的表达能力可能不如flux, 我想先用flux生成图片，然后作为风格图片，增强其为本对图像的表达能力。

demo双人风格化效果是用文本控制的，比如线条/赛博朋克风等，比较依赖底模的能力。如果用flux先生成风格化的图片再用这个可能效果不太好
