### ISSUE TITLE
Is LoRA applied to image prompt embed?

### ISSUE THREAD

**Issue by chrisway613** [RedAIGC/StoryMaker#27]
I saw the code implementation is conflict with the formula (8) in paper, which said the LoRA layers are also applied to image prompt embed:
https://github.com/RedAIGC/StoryMaker/blob/8cb2b12ed1c689cb7827151ace748abd5c8b90a0/ip_adapter/attention_processor_faceid.py#L184

So, is a slip of pen in paper?

**Comment by RedAIGC** [comment]
> I saw the code implementation is conflict with the formula (8) in paper, which said the LoRA layers are also applied to image prompt embed:
> 
> https://github.com/RedAIGC/StoryMaker/blob/8cb2b12ed1c689cb7827151ace748abd5c8b90a0/ip_adapter/attention_processor_faceid.py#L184
> 
> So, is a slip of pen in paper?

Thanks for the correction. The formula in the paper is indeed wrong. Lora only works on text embed. We will correct it in the future.

**Comment by chrisway613** [comment]
Thanks for your reply~! 
(btw, and I also waiting for the training code.)
