### ISSUE TITLE
InvalidProtobuf: [ONNXRuntimeError] 

### ISSUE THREAD

**Issue by sumansid** [RedAIGC/StoryMaker#4]
Looks like `buffalo_l` is broken

`InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./models/buffalo_l/1k3d68.onnx failed:Protobuf parsing failed.`

**Comment by RedAIGC** [comment]
Thanks for your attention, can you try this model [https://huggingface.co/huaquan/buffalo_l](url)?
