### ISSUE TITLE
Have you added watermark in the model ?

### ISSUE THREAD

**Issue by ApolloRay** [RedAIGC/StoryMaker#7]
![ldh_cloth_0](https://github.com/user-attachments/assets/1b3a9d84-2f26-4509-a5b8-c7fdbfa4cd87)
![ldh_cloth_1](https://github.com/user-attachments/assets/2b604382-f7c5-4bc6-8128-92c986ee23cd)
![ldh_cloth_2](https://github.com/user-attachments/assets/41578812-4a38-4384-b4c4-32d8ab524679)
![ldh_cloth_3](https://github.com/user-attachments/assets/e8a6162e-413c-4aea-8e59-471798b6838f)
![ldh_tsy666_0](https://github.com/user-attachments/assets/8d95ab1d-5ae1-4424-be82-75a557289fb0)
![ldh_tsy666_1](https://github.com/user-attachments/assets/7a309857-6098-4b2b-8eac-01293a0565ec)
![ldh_tsy666_2](https://github.com/user-attachments/assets/ecd98b51-c2ce-4948-89d0-8f10b3cd99ab)
![ldh_tsy666_3](https://github.com/user-attachments/assets/1bb48202-b10d-4b38-bc56-8fe1d1e3a2a7)
![ldh666_0](https://github.com/user-attachments/assets/f702ca3a-03a4-4d6f-8491-6850bcb294cf)
![ldh666_1](https://github.com/user-attachments/assets/5315fb7c-32b1-45a0-a19c-567a7088d90e)
![ldh666_2](https://github.com/user-attachments/assets/1e1d191b-4e3c-418a-86dc-3f486a16baed)
![ldh666_3](https://github.com/user-attachments/assets/8823fe2c-cf05-4fcb-a6f5-6d6ca4106b20)
Demo results have a strange watermark.

**Comment by ApolloRay** [comment]
Ok, I know it. Because there is a watermark in ldh image, god please. Hhhhhh

**Comment by RedAIGC** [comment]
Thanks for your attention, yes, you found it, we should change this picture
