### ISSUE TITLE
Issue with Facial Shadows and Multiple Arms

### ISSUE THREAD

**Issue by touchwolf** [RedAIGC/StoryMaker#8]
Hi, may I ask which base model you are using for training? I have been using the RealcartoonXL series as the base model, but when generating images of Andy Lau, I encountered issues with strange facial shadows and multiple arms.

**Comment by RedAIGC** [comment]
> Hi, may I ask which base model you are using for training? I have been using the RealcartoonXL series as the base model, but when generating images of Andy Lau, I encountered issues with strange facial shadows and multiple arms.
Thank you for your attention. By default, we use [https://huggingface.co/huaquan/YamerMIX_v11](url) as the base model. Now the effect is indeed a bit overfitting. We are optimizing it. Or you can try running it a few more times or lowering the ip_adapter_scale and lora_scale.
